### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by thisischrisj** [jeromeetienne/threex.colliders#5]
Colliders and ColliderHelpers leak memory when the related object is removed. Maybe consider adding `dispose` methods that can be called when the "colliding" Object3D is disposed.

**Comment by jeromeetienne** [comment]
care to explain the bug more closely ? to point at some code with some explainations :)

**Comment by thisischrisj** [comment]
Yes, sorry Jerome.

Suppose we have the following code (assuming we've already set up a scene, camera, renderer, etc...):

```
for(var i=0; i < 100000; i++)
{
    // Create mesh
    var geometry = new THREE.SphereGeometry( 0.9, 32, 16);
    var material	= new THREE.MeshNormalMaterial();
    var mesh = new THREE.Mesh( geometry, material );
    mesh.name = i;
    scene.add( mesh );

    // Create collider
    var collider	= THREEx.Collider.createFromObject3d(mesh);
    collider.addEventListener('contactEnter', function(otherCollider)
    {
        // Some event driven code
        ...
    });

    // Create helper
    var helper = new THREEx.ColliderHelper(collider);
    helper.material.color.set('green');
    scene.add(helper);

    // Remove mesh and clean up memory
    // Taken from: http://stackoverflow.com/questions/22565737/cleanup-threejs-scene-leak
    scene.remove(mesh);
    mesh.geometry.dispose();
    mesh.geometry = undefined;
    mesh.material.dispose();
    mesh.material = undefined;
    mesh = undefined;
}
```

After running this code, we would have cleaned up all memory associated with the meshes but we'd still have 100000 instances of THREEx.Collider and THREEx.ColliderHelper.

It would be useful to include dispose methods for each which would:
 - unbind all events,
 - clean up the internals THREE.js objects, geometry, materials,
 - remove them from the scene,
 - etc...

This could be done manually by the user but the logic should really be packages up inside each "class". That way, if the internal logic changes the user is still confident that a call to collider.dispose() / helper.dispose() cleans up all memory allocated internally. That is, they don't need to refactor their code every time the library is updated.

The final part of the above code would then become:

```
    scene.remove(mesh);
    mesh.geometry.dispose();
    mesh.geometry = undefined;
    mesh.material.dispose();
    mesh.material = undefined;
    mesh = undefined;
    collider.dispose();
    helper.dispose();
```

**Comment by jeromeetienne** [comment]
good point! im all willing to make the change if memory is leaked. 

but this change is big (as i need to do it here and in 60 others extensions :) ) so i would like to be sure. can you help me find docs on why such case wouldnt be handled by garbage collection ?

**Comment by thisischrisj** [comment]
Hey Jerome, the objects wouldn't be handled by garbage collection because they aren't candidates. Garbage collection will only clean-up memory when there are no variables referencing the memory used by the object or it's child objects.

Based on the code example, the scene would be one object still holding a reference (to the ColliderHelper at least). On dispose, it should remove itself from the scene. 

With regards to Colliders, they have object stored internally as properties (e.g. this.object3d, this.shape, this.updatedBox3) which would need disposing of first. I'm not 100% but I think any event listeners also need removing before an object qualifies for garbage collection.

Here are a links I usually refer to when verifying "clean-up" in Three.js:
 - http://mrdoob.github.io/three.js/examples/webgl_test_memory.html
 - http://mrdoob.github.io/three.js/examples/webgl_test_memory2.html
 - http://stackoverflow.com/questions/22565737/cleanup-threejs-scene-leak

**Comment by jeromeetienne** [comment]
thanks for answering!

In my optinion, i think the actual definition would be "Garbage collection will only clean-up memory when there are no variables **currently used** referencing the memory used by the object or it's child objects", the difference being that if i no more refere to a variable, suddently all the property of this object will be candidate to gc too.

see what i mean ? and if it is the case... we dont need a .dispose() in collider, this is how it is code. Now i may be wrong :) 

if i am wrong, i would love to know. lets look some more on when a variable is gc 

http://stackoverflow.com/questions/22565737/cleanup-threejs-scene-leak <- in those, what is disposed is the webgl memory, not the js memory

**Comment by jeromeetienne** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#Release_when_the_memory_is_not_needed_anymore

interesting link! seems like you are right :)

**Comment by jeromeetienne** [comment]
>  This algorithm reduces the definition of "an object is not needed anymore" to "an object is unreachable".

please, read the mark and sweep paragraph. does this change how you see it ?

It seems that the internal references inside colliders wont affect its ability to be collect. this is how i read it, i would love to hear what you think

**Comment by thisischrisj** [comment]
Hi Jerome, I see your point and agree that, on the surface, it doesn't appear as though there's a leak. If the objects become unreachable then the memory associated with them should be removed.

To be honest, I always wondered why, when removing a mesh in Three.js, you had to dispose of the geometry and textures manually. Why weren't these just taken care of by garbage collection? Having scanned through the Three.js source I think your right - `dispose()` is a WebGL clean-up method as opposed to JS clean-up. In particularly, `dispose()` is used to delete buffers and decrement some internal Three.js counters.

This raises another point though - if garbage collection is managing memory from a JS perspective, where are the WebGL buffers being cleaned up? It's possible that they are dealt with by GC at the same time. If not, then (taking `THREEx.ColliderBox3` as an example) there are a few `new THREE.Box3()` calls in there that need "disposing" of manually when the JS object isn't referenced anymore.

With this in mind, there might be another issue. Every call to `update()` results in a new shape being assigned to `this.updatedBox3` . Presumably, the shape *previously* assigned would be cleaned up by garbage collection but the WebGL buffers wouldn't. If that's the case, then this isn't just limited to unreferenced colliders. Every call to update would be incrementing the buffer count.

I'm only hypothesising at this stage and I could be way off the mark. I could do with setting up a test case and then observing memory usage but it might be the weekend before I get chance.

As an aside, I think the point still stands for ColliderHelpers though. Since they are added to the scene, there should be a convenience method that removes them from the scene, cleans up their geometry, textures, events, etc.. Particularly important in this case since `geometry` and `material` are assigned to local/internal variables so the user can't call `dispose()` on them manually.

**Comment by thisischrisj** [comment]
What am I talking about?

Sorry Jerome, I'm confusing `Box3` and `Geometry`. Since `Box3` is purely a JS object I can't see an issue with `THREEx.Collider`s.

There is some clean-up required with `ColliderHelpers` though. I've wasted enough of your time with this so I'll create a pull request this weekend and add a `dispose` for those to deal with the geometry & material objects defined in the local scope. 

Just to be sure, I'll set-up a test case and confirm whether there's even an issue in the first place and that any changes I make correct it.

**Comment by jeromeetienne** [comment]
not really to be honest. i keep rereading your previous answer and i cant understand it.

I would love a test case, that will be the best. but how to prove that the memory is freed or is leaked ?

```To be honest, I always wondered why, when removing a mesh in Three.js, you had to dispose of the geometry and textures manually.```. Just one thing about ```.dispose()``` in three.js, this is to free webgl memory. as it isnt handled at all via javascript gc it has to be explicitly freed. this is a completly different case.

**Comment by thisischrisj** [comment]
Totally my fault. When I was looking at this last night, I was *reading* `Box3` but was *thinking* `BoxGeometry`. A `BoxGeometry` object would need to be cleaned up with `dispose()` but `Box3` isn't a WebGl object and is fine to leave for the garbage collector.

With regards to `ColliderHelper`s, let's go back to my first example:

```
for(var i=0; i < 100000; i++)
{
    // Create mesh
    var geometry = new THREE.SphereGeometry( 0.9, 32, 16);
    var material    = new THREE.MeshNormalMaterial();
    var mesh = new THREE.Mesh( geometry, material );
    mesh.name = i;
    scene.add( mesh );

    // Create collider
    var collider    = THREEx.Collider.createFromObject3d(mesh);
    collider.addEventListener('contactEnter', function(otherCollider)
    {
        // Some event driven code
        ...
    });

    // Create helper
    var helper = new THREEx.ColliderHelper(collider);
    helper.material.color.set('green');
    scene.add(helper);

    // Remove mesh, clean up memory
    // Taken from: http://stackoverflow.com/questions/22565737/cleanup-threejs-scene-leak
    scene.remove(mesh);
    mesh.geometry.dispose();
    mesh.geometry = undefined;
    mesh.material.dispose();
    mesh.material = undefined;
    mesh = undefined;

    // Now clean-up colliders
    collider.removeEventListener('contactEnter');
    collider = undefined;
    scene.remove(helper);
    helper = undefined;
}
```

The last 2 lines don't fully clean up all the memory for the helper. Internally we have these two lines:

```
var geometry	= new THREE.BoxGeometry(1,1,1)
var material	= new THREE.MeshBasicMaterial({
    wireframe	: true
})
```

In order to clean-up all the memory used by the helper we would also need to clean-up the WebGL buffers for `geometry` and `material`. Because they are defined in the local scope the user can't access them directly and therefore can't clean them up with something like:

```
scene.remove(helper);
helper.geometry.dispose();
helper.material.dispose();
helper = undefined;
```

Does that make sense?

**Comment by jeromeetienne** [comment]
ah yes! i understand now :) i will do the modification for THREEx.ColliderHelper to have .dispose()

but just to be sure we agree. this is the conclusion of our chat.

- all the javascript object are freeed by normal javascript GC
- all the webgl object are freed explicitly by .dispose() ?

do we agree ?

**Comment by jeromeetienne** [comment]
i commited the patch, what do you think ?

**Comment by thisischrisj** [comment]
That's exactly right :)

I'm working on a project this weekend where I'm adding and removing a lot of collidable objects. I'll run some tests to check if we've missed anything.

Thanks for the quick update!

**Comment by thisischrisj** [comment]
Just checked. That looks good to me. Thanks again.
